../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0043/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0042/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/tactics/TA0040/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1595/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1595/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1595/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1595/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1592/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1592/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1592/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1592/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1592/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1589/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1589/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1589/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1589/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1590/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1591/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1591/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1591/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1591/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1591/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1598/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1598/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1598/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1598/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1598/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1597/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1597/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1597/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1596/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1593/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1593/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1593/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1593/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1594/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1650/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1583/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1586/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1586/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1586/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1586/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1584/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1587/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1587/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1587/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1587/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1587/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1585/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1585/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1585/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1585/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1588/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1608/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1659/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1189/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1190/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1133/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1200/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1566/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1566/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1566/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1566/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1566/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1091/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1195/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1195/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1195/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1195/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1199/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1078/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1078/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1078/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1078/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1078/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1651/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1059/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1609/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1610/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1203/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1559/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1559/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1559/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1559/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1106/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1053/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1648/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1129/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1072/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1569/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1569/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1569/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1204/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1204/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1204/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1204/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1047/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1098/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1197/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/013/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/014/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1547/015/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1037/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1176/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1554/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1136/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1136/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1136/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1136/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1543/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1543/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1543/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1543/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1543/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/013/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/014/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/015/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1546/016/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1574/013/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1525/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1556/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1137/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1653/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1542/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1505/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1205/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1205/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1205/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1548/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1134/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1484/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1484/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1484/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1611/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1068/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/013/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/014/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1055/015/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1612/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1622/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1140/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1480/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1480/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1211/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1222/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1222/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1222/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1564/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1562/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1656/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1070/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1202/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1036/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1578/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1112/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1601/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1601/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1601/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1599/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1599/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1027/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1647/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1620/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1207/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1014/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1553/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/009/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/013/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1218/014/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1216/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1216/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1221/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1127/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1127/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1535/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1550/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1550/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1550/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1550/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1550/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1497/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1497/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1497/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1497/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1600/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1600/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1600/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1220/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1557/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1557/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1557/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1557/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1110/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1110/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1110/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1110/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1110/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1555/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1212/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1187/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1606/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1606/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1606/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1056/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1056/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1056/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1056/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1056/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1111/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1621/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1040/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1003/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1528/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1649/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1558/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1558/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1558/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1558/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1558/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1539/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1552/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1087/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1087/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1087/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1087/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1087/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1010/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1217/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1580/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1538/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1526/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1619/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1613/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1652/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1482/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1083/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1615/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1654/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1046/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1135/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1201/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1120/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1069/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1069/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1069/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1069/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1057/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1012/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1018/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1518/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1518/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1082/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1614/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1614/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1016/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1016/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1016/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1049/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1033/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1124/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1210/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1534/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1570/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1563/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1563/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1563/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/006/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/007/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1021/008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1080/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1560/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1560/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1560/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1560/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1123/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1119/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1185/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1115/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1530/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1602/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1602/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1602/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1213/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1213/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1213/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1213/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1005/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1039/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1025/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1074/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1074/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1074/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1114/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1114/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1114/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1114/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1113/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1125/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1071/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1071/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1071/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1071/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1071/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1092/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1132/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1132/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1132/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1001/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1001/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1001/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1568/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1568/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1568/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1568/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1573/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1573/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1573/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1008/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1105/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1104/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1095/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1571/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1572/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1090/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1090/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1090/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1090/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1090/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1219/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1102/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1102/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1102/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1102/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1020/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1020/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1030/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1048/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1048/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1048/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1048/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1041/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1011/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1011/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1052/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1052/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1567/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1567/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1567/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1567/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1567/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1029/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1537/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1531/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1485/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1486/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1565/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1565/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1565/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1565/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1491/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1491/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1491/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1561/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1561/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1561/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1499/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1499/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1499/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1499/003/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1499/004/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1657/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1495/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1490/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1498/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1498/001/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1498/002/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1496/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1489/ https://attack.mitre.org/
../../file-utils/get-json-from-url2.py https://attack.mitre.org/techniques/T1529/ https://attack.mitre.org/
